# Generated by Django 5.0.6 on 2024-05-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_images_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter_price',
            old_name='name',
            new_name='price',
        ),
    ]
