# Generated by Django 5.0.6 on 2024-05-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_rename_name_filter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Renewed', 'Renewed'), ('Used', 'Used')], max_length=100),
        ),
    ]
