# Generated by Django 5.0.6 on 2024-05-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('1 To 1000', '1 To 1000'), ('1000 To 5000', '1000 To 5000'), ('5000 To 10000', '5000 To 10000'), ('1000 To 10000', '1000 To 10000'), ('10000 To 20000', '10000 To 20000'), ('20000 To 30000', '20000 To 30000'), ('30000 To 40000', '30000 To 40000'), ('40000 To 50000', '40000 To 50000'), ('50000 To 60000', '50000 To 60000'), ('60000 To 70000', '60000 To 70000'), ('70000 To 80000', '70000 To 80000'), ('80000 To 90000', '80000 To 90000'), ('90000 To 100000', '90000 To 100000')], max_length=60),
        ),
    ]
