# Generated by Django 5.0.6 on 2024-05-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
    ]
