# Generated by Django 5.0.6 on 2024-05-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_alter_contactus_options_alter_images_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
