# Generated by Django 5.0.6 on 2024-06-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0020_remove_product_wishlisted_product_wishlisted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Order Placed', 'Order Placed'), ('Dispatch', 'Dispatch'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Return', 'Return')], max_length=100, null=True),
        ),
    ]
