# Generated by Django 5.0.6 on 2024-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0023_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Order Processed'), (3, 'Order Shipped'), (4, 'Order En-route'), (5, 'Order Arrived')], default=1, max_length=100, null=True),
        ),
    ]
